In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
import string

In [2]:
df=pd.read_csv('D://DATA SCIENCE//email_spam_detector_dataset.csv')
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [3]:
df.shape

(5728, 2)

In [4]:
df.columns

Index(['text', 'spam'], dtype='object')

In [7]:
df.duplicated().sum()

33

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df.duplicated().sum()

0

In [10]:
df.isna().sum()

text    0
spam    0
dtype: int64

In [13]:
def cleaning(text):
    nopunc = [x for x in text if x not in string.punctuation]
    nopunc = "".join(nopunc)
    
    clean = [y for y in nopunc.split() if y not in stopwords.words('english')]
    return clean

In [14]:
df['text']=df['text'].apply(cleaning)

In [15]:
df.sample(5)

text  spam
2342  [Subject, book, review, great, job, vince, kno...     0
3856  [Subject, confidence, prc, summary, hi, vince,...     0
1821  [Subject, vince, kaminski, bio, hello, amy, at...     0
4101  [Subject, introduction, meeting, rac, london, ...     0
2913  [Subject, hello, vince, thank, update, back, o...     0

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
message = CountVectorizer(analyzer= cleaning).fit_transform(df.text)

In [20]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(message,df['spam'],test_size=0.20)

In [24]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train,y_train)


In [26]:
classifier.predict(X_train)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
y_train.values

array([0, 0, 1, ..., 1, 0, 0], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [29]:
pred = classifier.predict(X_train)

In [31]:
print("Confusion Matrix: \n", confusion_matrix(y_train, pred))

Confusion Matrix: 
 [[3463    0]
 [1091    2]]


In [33]:
print("Accuracy: \n", accuracy_score(y_train, pred))

Accuracy: 
 0.7605355575065847


In [34]:
classifier.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
y_test.values

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [37]:
pred = classifier.predict(X_test)

In [38]:
print("Confusion Matrix: \n", confusion_matrix(y_test, pred))

Confusion Matrix: 
 [[864   0]
 [275   0]]


In [39]:
print("Accuracy: \n", accuracy_score(y_test, pred))

Accuracy: 
 0.7585601404741001
